# Generated by Django 5.0.4 on 2024-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('summary', models.TextField()),
                ('skills', models.TextField(help_text='Separate skills with commas')),
                ('experience', models.TextField()),
                ('education', models.TextField()),
            ],
        ),
    ]
